config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "problems#index"
  resources :problems do
    resources :comments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :problem

  validates :comment,     presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :problem
end

app/models/grade.rb
class Grade < ActiveHash::Base
  self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '中学1年生' },
   { id: 3, name: '中学2年生' },
   { id: 4, name: '中学3年生' },
   { id: 5, name: '高校1年生' },
   { id: 6, name: '高校2年生' },
   { id: 7, name: '高校3年生' }
 ]
end

app/models/problem.rb
class Problem < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :grade

  validates :title,         presence: true
  validates :statement,     presence: true
  validates :answer,        presence: true
  validates :grade_id,      presence: true, numericality: { other_than: 1 } 

  belongs_to :user
  has_many :favorites
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname,      presence: true
  validates :email,         presence: true,     uniqueness: { case_sensitive: :false }
  validates :password,      presence: true,     format: {with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{6,}\z/}

  has_many :favorites
  has_many :comments
  has_many :problems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    #デフォルトで保存可能なemailとpassword以外の値が保存できるように。
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @problems = Problem.includes(:user)
  end

  def new
    @problem = Problem.new
  end

  def create
    # binding.pry
    @problem = Problem.new(problem_params)
    if @problem.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @problem = Problem.find(params[:id])
  end

  private

  def problem_params
    params.require(:problem).permit(:title, :statement, :answer, :grade_id).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareStudy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        TeX: { equationNumbers: { autoNumber: "AMS" }},
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"] ],
          processEscapes: true
        },
        "HTML-CSS": { matchFontHeight: false },
        displayAlign: "left",
        displayIndent: "2em"
      });
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/problems/_problem.html.erb
<li class='list'>
  <%= link_to problem_path(problem.id) do %>
  <div class='item-img-content'>
    <% if problem.grade_id == 2%>
      <%= image_tag "function-1.png", class: "item-img" %>
    <% elsif problem.grade_id == 3%>
      <%= image_tag "function-2.png", class: "item-img" %>
    <% elsif problem.grade_id == 4%>
      <%= image_tag "function-3.png", class: "item-img" %>
    <% elsif problem.grade_id == 5%>
      <%= image_tag "function1.png", class: "item-img" %>
    <% elsif problem.grade_id == 6%>
      <%= image_tag "function2.png", class: "item-img" %>
    <% elsif problem.grade_id == 7%>
      <%= image_tag "function3.png", class: "item-img" %>
    <% end%>
  </div>
  <div class='item-info'>
    <h3 class='item-name'>
      <%= problem.title %>
    </h3>
    <div class='item-price'>
      <div class='star-btn'>
        <%= image_tag "star.png", class:"star-icon" %>
        <span class='star-count'>0</span>
      </div>
    </div>
  </div>
  <% end %>
</li>

app/views/problems/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      Share Studyはみんなの学び場
    </h2>
    <p class='service-explain'>
      大人も子供も、みんなで学べる
    </p>
    <p class='service-explain'>
      いこいの場です
    </p>
  </div>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', new_problem_path, class: "subtitle" %>
    <ul class='item-lists'>
    <%= render partial: "problem", collection: @problems %>
    <% if @problems == nil %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "function.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end%>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出題する</span>
  <a href="/items/new">
    <%= image_tag 'study-icon.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%= render "shared/footer" %>

app/views/problems/new.html.erb
<%# JavaScriptファイルを読み込む。app/javascript/packs/problems/javatex.js %>
<%= javascript_pack_tag 'problems/javatex' %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">問題を入力</h2>
    <%= form_with model: @problem, url: problems_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%# 学年 %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          問題の対象学年
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:grade_id, Grade.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>

    <%# 問題文 %>
    <div class="new-items">
      <div class="weight-bold-text">
        問題のタイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          問題文
          <span class="indispensable">必須</span>
        </div>
        <div class="real-time">
          <%= f.text_area :statement, class:"items-text", id:"item-info1", placeholder:"" ,rows:"7" ,maxlength:"1000" %>
          <div class="javatex", id="latex1">
          </div>
        </div>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          解答
          <span class="indispensable">必須</span>
        </div>
        <div class="real-time">
          <%= f.text_area :answer, class:"items-text", id:"item-info2", placeholder:"" ,rows:"7" ,maxlength:"1000" %>
          <div class="javatex", id="latex2">
          </div>
        </div>
      </div>
    </div>
    <%# /商品名と商品説明 %>


    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出題する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/problems/show.html.erb
<%# JavaScriptファイルを読み込む。app/javascript/packs/problems/javatexShow.js %>
<%= javascript_pack_tag 'problems/javatexShow' %>

<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @problem.title %>
    </h2>
    <div class='item-img-content'>
    </div>
    <div class="item-price-box">
      <span class="item-price">
      </span>
      <span class="item-postage">
      </span>
    </div>

    <div class="problem-edit">
    <% if user_signed_in? %>
      <% if @problem.user.id == current_user.id %>
        <%= link_to '商品の編集', edit_problem_path(@problem.id), method: :get, class: "item-red-btn" %>
        <%= link_to '削除', problem_path, method: :delete, class:'item-destroy' %>
      <% end%>
    <% end%>
    </div>

    <div class="problem-statement", id="latex1">
      <%= @problem.statement %>
    </div>
    <div class="problem-answer", id="latex2">
      <span><%= @problem.answer %></span>
    </div>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な問題の通報</span>
      </div>
    </div>
  </div>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の問題
    </a>
    <a href="#" class="change-item-btn">
      後ろの問題 ＞
    </a>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、学べるwebページ
  </p>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SHARE STUDYについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to '利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SHARE STUDYを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SHARE STUDYについて</h2>
      <ul>
        <li><%= link_to 'SHARE STUDYガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'SHARE STUDYロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© SHARE STUDY</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class: "furima-icon"), root_path %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, root_path, class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>